server:
  port: 8088

spring:
    datasource:
        name: test1
        url: jdbc:mysql://localhost:3306/test
        username: rose
        password: 1234
        # 阿里云数据池
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        # thymeleaf的开发缓存关闭
    thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      encoding: utf-8
      mode: LEGACYHTML5
    devtools:
      livereload:
        enabled: true
    resources:
      static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
    mvc:
      static-path-pattern: /**

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.grddes

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging.level.com.grddes: debug

